Repository cesko-digital/volebni-kalkulacka-2022, pull requests merged in 2022-11, with the labels that each got.

#220 Add Darujme.cz widget to results
  frontend/src/routes/result/ResultPage.vue
Labels: enhancement

#261 November homepage update
  frontend/src/components/design-system/layout/MasonryGrid.vue
  frontend/src/routes/index/IndexPage.vue
Labels: frontend

#262 Deploy production manually only
  .github/workflows/backend-deploy.yaml
  .github/workflows/data-deploy.yaml
  .github/workflows/frontend.yaml
Labels: devops
