Repository cesko-digital/volebni-kalkulacka-2022, pull requests merged in 2023-05, with the labels that each got.

#501 Clean up GitHub Actions workflows
  .github/workflows/backend-deploy.yaml
  .github/workflows/data-deploy.yaml
  .github/workflows/frontend.yaml
Labels: devops, refactoring

#500 Clean up infrastructure
  .github/CODEOWNERS
  README.md
  infrastructure/README.md
  infrastructure/aws/backend.tf
  infrastructure/aws/cloudfront.tf
  infrastructure/aws/data.tf
  infrastructure/aws/dynamodb.tf
  infrastructure/aws/frontend.tf
  infrastructure/aws/newrelic.tf
  infrastructure/aws/terraform.tf
  infrastructure/aws/variables.tf
Labels: refactoring

#502 Add Node Version Manager
  .github/workflows/clean-up-preview-database.yaml
  .github/workflows/frontend.yaml
  frontend/.nvmrc
  frontend/docs/development.md
Labels: devops, dependencies

#485 Remove pre-commit
  .pre-commit-config.yaml
  Makefile
  README.md
Labels: devops

#410 Clean up data
  data/kalkulacka/calculators.json
  data/kalkulacka/prezidentske-2023-kolo-1/global.json
  data/kalkulacka/prezidentske-2023-kolo-test/global.json
  data/kalkulacka/prezidentske-2023-kolo-test/pro-kazdeho-1-kolo.json
  data/kalkulacka/prezidentske-2023-kolo-test/pro-mladistve-1-kolo.json
  data/kalkulacka/prezidentske-2023-kolo-test/pro-politicke-nadsence-1-kolo.json
  data/kalkulacka/prezidentske-2023/1-kolo.json
  data/kalkulacka/prezidentske-2023/pro-kazdeho-1-kolo.json
  data/kalkulacka/prezidentske-2023/pro-kazdeho.json
  data/kalkulacka/prezidentske-2023/pro-mlade.json
  data/kalkulacka/prezidentske-2023/pro-mladistve-1-kolo.json
  data/kalkulacka/prezidentske-2023/pro-nadsence.json
  data/kalkulacka/prezidentske-2023/pro-politicke-nadsence-1-kolo.json
Labels: data, refactoring

#386 Add missing `fb:app_id` meta tag
  frontend/index.html
Labels: bug
