Repository cesko-digital/volebni-kalkulacka-2022, pull requests merged in 2023-04, with the labels that each got.

#489 Fix incorrect DB variable example
  frontend/.env.development.local.example
  frontend/docs/development.md
Labels: documentation

#488 Hotfix Prettier dotfiles resolution
  frontend/.prettierrc.yaml
Labels: bug, devops

#491 Update dependencies
  frontend/.env.production
  frontend/.prettierrc.yaml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/index/IndexPage.vue
Labels: dependencies

#486 Add email login/registration flow
  frontend/.env.development
  frontend/api/auth/index.ts
  frontend/docs/development.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/email.svg
  frontend/src/components/design-system/containers/ElectionCardComponent.stories.ts
  frontend/src/components/design-system/containers/ElectionCardComponent.vue
  frontend/src/components/design-system/input/ButtonComponent.vue
  frontend/src/components/design-system/input/FormComponent.vue
  frontend/src/components/design-system/input/TextInputComponent.vue
  frontend/src/components/design-system/navigation/NavigationBar.vue
  frontend/src/components/design-system/typography/BodyText.vue
  frontend/src/components/design-system/typography/ButtonText.vue
  frontend/src/components/design-system/typography/TitleText.vue
  frontend/src/main.ts
  frontend/src/routes/index/IndexPage.vue
  frontend/src/routes/profile/AuthPageVue.vue
  frontend/src/routes/profile/EmailAuthPageVue.vue
  frontend/src/routes/profile/EmailFormPageVue.vue
  frontend/src/routes/profile/LoginPageVue.vue
  frontend/src/routes/profile/ProfileCardComponent.vue
  frontend/src/routes/profile/ProfileSettingsPage.vue
  frontend/src/routes/profile/RegisterPageVue.vue
  frontend/src/routes/profile/SocialMediaConnectComponent.vue
  frontend/src/server/mailing.ts
Labels: feature
