Repository cesko-digital/volebni-kalkulacka-2022, pull requests merged in 2023-08, with the labels that each got.

#534 Fix typo on Slovak home
  frontend/src/routes/index/IndexPage.vue
Labels: bug

#531 Implement frontend internationalization
  frontend/.env.development
  frontend/.env.production
  frontend/.env.test
  frontend/package-lock.json
  frontend/package.json
  frontend/src/i18n/index.ts
  frontend/src/i18n/locales/cs.json
  frontend/src/i18n/locales/sk.json
  frontend/src/main.ts
  frontend/tsconfig.app.json
  frontend/vite.config.ts
Labels: feature

#535 Add example translation & docs
  frontend/.env.development
  frontend/.env.preview
  frontend/.env.production
  frontend/docs/internationalization.md
  frontend/src/i18n/locales/cs.json
  frontend/src/i18n/locales/sk.json
  frontend/src/routes/index/IndexPage.vue
Labels: documentation, refactoring

#515 Draft new blank data schema
  data/example/volebnikalkulacka.cz/doprava-v-praze/calculator.json
  data/example/volebnikalkulacka.cz/doprava-v-praze/candidates-answers.json
  data/example/volebnikalkulacka.cz/doprava-v-praze/candidates.json
  data/example/volebnikalkulacka.cz/doprava-v-praze/questions.json
  data/example/volebnikalkulacka.cz/green-deal/calculator-group.json
  data/example/volebnikalkulacka.cz/green-deal/pro-experty/calculator.json
  data/example/volebnikalkulacka.cz/green-deal/pro-experty/candidates-answers.json
  data/example/volebnikalkulacka.cz/green-deal/pro-experty/candidates.json
  data/example/volebnikalkulacka.cz/green-deal/pro-experty/questions.json
  data/example/volebnikalkulacka.cz/green-deal/pro-kazdeho/calculator.json
  data/example/volebnikalkulacka.cz/green-deal/pro-kazdeho/candidates-answers.json
  data/example/volebnikalkulacka.cz/green-deal/pro-kazdeho/candidates.json
  data/example/volebnikalkulacka.cz/green-deal/pro-kazdeho/questions.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/1-kolo/calculator.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/1-kolo/candidates-answers.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/1-kolo/candidates.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/1-kolo/questions.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/2-kolo/calculator.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/2-kolo/candidates-answers.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/2-kolo/candidates.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/2-kolo/questions.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/calculator-group.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/election.json
  data/schemas/answer.schema.json
  data/schemas/answers.schema.json
  data/schemas/calculator-group.schema.json
  data/schemas/calculator-groups.schema.json
  data/schemas/calculator.schema.json
  data/schemas/calculators.schema.json
  data/schemas/candidate.schema.json
  data/schemas/candidates-answers.schema.json
  data/schemas/candidates.schema.json
  data/schemas/district.schema.json
  data/schemas/election.schema.json
  data/schemas/elections.schema.json
  data/schemas/package-lock.json
  data/schemas/package.json
  data/schemas/question.schema.json
  data/schemas/questions.schema.json
  data/schemas/round.schema.json
  data/schemas/variant.schema.json
  frontend/docs/data.md
Labels: data, refactoring

#537 Add candidates, persons & organizations schemas
  data/example/volebnikalkulacka.cz/doprava-v-praze/candidates.json
  data/example/volebnikalkulacka.cz/doprava-v-praze/organizations.json
  data/example/volebnikalkulacka.cz/doprava-v-praze/persons.json
  data/example/volebnikalkulacka.cz/green-deal/pro-experty/candidates.json
  data/example/volebnikalkulacka.cz/green-deal/pro-experty/organizations.json
  data/example/volebnikalkulacka.cz/green-deal/pro-experty/persons.json
  data/example/volebnikalkulacka.cz/green-deal/pro-kazdeho/candidates.json
  data/example/volebnikalkulacka.cz/green-deal/pro-kazdeho/organizations.json
  data/example/volebnikalkulacka.cz/green-deal/pro-kazdeho/persons.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/1-kolo/candidates.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/1-kolo/organizations.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/1-kolo/persons.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/2-kolo/candidates.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/2-kolo/organizations.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/2-kolo/persons.json
  data/schemas/candidate.schema.json
  data/schemas/organization.schema.json
  data/schemas/organizations.schema.json
  data/schemas/package.json
  data/schemas/person.schema.json
  data/schemas/persons.schema.json
  frontend/docs/data.md
Labels: data, refactoring

#540 Add time attributes to schemas
  data/example/volebnikalkulacka.cz/doprava-v-praze/calculator.json
  data/example/volebnikalkulacka.cz/green-deal/calculator-group.json
  data/example/volebnikalkulacka.cz/green-deal/pro-experty/calculator.json
  data/example/volebnikalkulacka.cz/green-deal/pro-kazdeho/calculator.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/1-kolo/calculator.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/2-kolo/calculator.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/calculator-group.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/election.json
  data/schemas/calculator-group.schema.json
  data/schemas/calculator.schema.json
  data/schemas/election.schema.json
Labels: enhancement, data, refactoring

#541 Add names to schemas
  data/example/volebnikalkulacka.cz/doprava-v-praze/calculator.json
  data/example/volebnikalkulacka.cz/doprava-v-praze/organizations.json
  data/example/volebnikalkulacka.cz/doprava-v-praze/persons.json
  data/example/volebnikalkulacka.cz/green-deal/calculator-group.json
  data/example/volebnikalkulacka.cz/green-deal/pro-experty/organizations.json
  data/example/volebnikalkulacka.cz/green-deal/pro-experty/persons.json
  data/example/volebnikalkulacka.cz/green-deal/pro-kazdeho/organizations.json
  data/example/volebnikalkulacka.cz/green-deal/pro-kazdeho/persons.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/1-kolo/organizations.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/1-kolo/persons.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/2-kolo/organizations.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/2-kolo/persons.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/election.json
  data/schemas/calculator-group.schema.json
  data/schemas/calculator.schema.json
  data/schemas/election.schema.json
  data/schemas/organization.schema.json
  data/schemas/person.schema.json
Labels: enhancement, data, refactoring

#542 Add question attributes to schemas
  data/example/volebnikalkulacka.cz/doprava-v-praze/questions.json
  data/example/volebnikalkulacka.cz/green-deal/pro-experty/questions.json
  data/example/volebnikalkulacka.cz/green-deal/pro-kazdeho/questions.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/1-kolo/questions.json
  data/example/volebnikalkulacka.cz/prezidentske-2023/2-kolo/questions.json
  data/schemas/question.schema.json
Labels: data, refactoring

#550 Generate types from schemas
  data/package-lock.json
  data/package.json
  data/schemas/package-lock.json
  data/schemas/package.json
  data/types/answer.ts
  data/types/answers.ts
  data/types/calculator.ts
  data/types/calculatorGroup.ts
  data/types/calculatorGroups.ts
  data/types/calculators.ts
  data/types/candidate.ts
  data/types/candidates.ts
  data/types/candidatesAnswers.ts
  data/types/district.ts
  data/types/election.ts
  data/types/elections.ts
  data/types/organization.ts
  data/types/organizations.ts
  data/types/person.ts
  data/types/persons.ts
  data/types/question.ts
  data/types/questions.ts
  data/types/round.ts
  data/types/variant.ts
Labels: data, refactoring

#547 Swap about us page for Slovak version
  frontend/src/routes/about-us/AboutUsPage.vue
Labels: enhancement

#551 Deprecate old schemas
  frontend/src/common/dataFetch.ts
  frontend/src/common/restApi.ts
  frontend/src/common/resultParser.ts
  frontend/src/components/QuestionCard.vue
  frontend/src/components/design-system/containers/ElectionCardComponent.vue
  frontend/src/routes/comparison/ComparisonGrid.vue
  frontend/src/routes/comparison/ComparisonPage.vue
  frontend/src/routes/district-selection/DistrictSelectionPage.vue
  frontend/src/routes/guide/GuidePage.vue
  frontend/src/routes/profile/ElectionCardWrapperComponent.vue
  frontend/src/routes/profile/SocialMediaConnectComponent.vue
  frontend/src/routes/question/QuestionCard.vue
  frontend/src/routes/question/QuestionPage.vue
  frontend/src/routes/recap/RecapPage.vue
  frontend/src/routes/recap/RecapQuestionCard.vue
  frontend/src/routes/result/ResultCardContacts.vue
  frontend/src/routes/result/ResultPage.vue
  frontend/src/stores/electionStore.ts
  frontend/src/types/calculator.d.ts
  frontend/src/types/calculators.d.ts
  frontend/src/types/candidate-answer.d.ts
  frontend/src/types/candidate.d.ts
  frontend/src/types/contact.d.ts
  frontend/src/types/election.d.ts
  frontend/src/types/party.d.ts
  frontend/src/types/question.d.ts
Labels: refactoring

#552 Fix paths in data NPM scripts
  data/package.json
Labels: bug, data

#553 Add translations vol. 1
  frontend/src/components/DonateBlock.vue
  frontend/src/components/FooterMultiWord.vue
  frontend/src/components/QuestionCandidateFilter.vue
  frontend/src/components/QuestionTagFilter.vue
  frontend/src/i18n/locales/cs.json
  frontend/src/i18n/locales/sk.json
Labels: refactoring

#554 Add translations vol. 2
  frontend/src/i18n/locales/cs.json
  frontend/src/i18n/locales/sk.json
  frontend/src/routes/data-protection/DataProtectionPage.vue
  frontend/src/routes/profile/AuthPageVue.vue
  frontend/src/routes/profile/EmailAuthPageVue.vue
  frontend/src/routes/profile/EmailFormPageVue.vue
  frontend/src/routes/profile/ProfilePage.vue
  frontend/src/routes/profile/ProfileSettingsPage.vue
  frontend/src/routes/profile/SocialMediaConnectComponent.vue
Labels: refactoring

#555 Add translations vol. 3
  frontend/src/components/FooterMultiWord.vue
  frontend/src/components/QuestionTagFilter.vue
  frontend/src/components/WantToKnowMore.vue
  frontend/src/i18n/locales/cs.json
  frontend/src/i18n/locales/sk.json
  frontend/src/routes/comparison/ComparisonGrid.vue
  frontend/src/routes/comparison/ComparisonPage.vue
  frontend/src/routes/error/ErrorPage.vue
  frontend/src/routes/question/QuestionBottomBar.vue
  frontend/src/routes/question/QuestionPage.vue
  frontend/src/routes/recap/RecapPage.vue
  frontend/src/routes/recap/RecapQuestionCard.vue
  frontend/src/routes/result/ResultCandidateCard.vue
  frontend/src/routes/result/ResultCardContacts.vue
  frontend/src/routes/result/ResultCategory.vue
  frontend/src/routes/result/ResultPage.vue
  frontend/src/routes/result/ResultShareModal.vue
  frontend/src/routes/share/SharePage.vue
Labels: refactoring

#561 Add guide translations
  frontend/src/i18n/locales/cs.json
  frontend/src/i18n/locales/sk.json
  frontend/src/routes/guide/GuidePage.vue
Labels: refactoring

#563 Fix translations
  frontend/src/components/design-system/navigation/NavigationBar.vue
  frontend/src/i18n/locales/cs.json
  frontend/src/i18n/locales/sk.json
  frontend/src/main.ts
  frontend/src/routes/comparison/ComparisonPage.vue
  frontend/src/routes/guide/GuidePage.vue
  frontend/src/routes/profile/AuthPageVue.vue
  frontend/src/routes/profile/EmailFormPageVue.vue
  frontend/src/routes/question/QuestionBottomBar.vue
  frontend/src/routes/question/QuestionPage.vue
  frontend/src/routes/recap/RecapPage.vue
  frontend/src/routes/recap/RecapQuestionCard.vue
  frontend/src/routes/result/ResultCandidateCard.vue
  frontend/src/routes/result/ResultPage.vue
  frontend/src/routes/result/ResultShareModal.vue
  frontend/src/routes/share/SharePage.vue
Labels: bug, refactoring

#562 Translate hardcoded methodology page
  frontend/src/i18n/locales/cs.json
  frontend/src/i18n/locales/sk.json
  frontend/src/routes/questions-methodology/QuestionsMethodologyPageVue.vue
  frontend/src/routes/questions-methodology/QuestionsMethodologyText.md
Labels: refactoring

#564 Slovak launch hacks
  frontend/src/components/design-system/navigation/NavigationBar.vue
  frontend/src/routes/result/ResultPage.vue
Labels: refactoring

#539 Add data for Slovak national council voting calculator
  .gitignore
  data/instance/volebnakalkulacka.sk/nrsr-2023/calculator-group.json
  data/instance/volebnakalkulacka.sk/nrsr-2023/election.json
  data/instance/volebnakalkulacka.sk/nrsr-2023/inventura-2020-2023/calculator.json
  data/instance/volebnakalkulacka.sk/nrsr-2023/inventura-2020-2023/candidates-answers.json
  data/instance/volebnakalkulacka.sk/nrsr-2023/inventura-2020-2023/candidates.json
  data/instance/volebnakalkulacka.sk/nrsr-2023/inventura-2020-2023/organizations.json
  data/instance/volebnakalkulacka.sk/nrsr-2023/inventura-2020-2023/persons.json
  data/instance/volebnakalkulacka.sk/nrsr-2023/inventura-2020-2023/questions.json
Labels: data

#556 Hack for fetching Slovak national voting calculator data
  data/kalkulacka/calculators.json
  frontend/index.html
  frontend/src/common/dataFetch.ts
  frontend/src/main.ts
  frontend/src/routes/comparison/ComparisonGrid.vue
  frontend/src/routes/guide/GuidePage.vue
  frontend/src/routes/index/IndexPage.vue
  frontend/src/routes/result/ResultPage.vue
  frontend/tsconfig.app.json
Labels: refactoring

#567 Fix questions for Slovak national voting calculator data
  data/instance/volebnakalkulacka.sk/nrsr-2023/inventura-2020-2023/questions.json
Labels: bug, data

#568 Enhance Slovak translations and copy
  frontend/src/common/dataFetch.ts
  frontend/src/i18n/locales/sk.json
  frontend/src/routes/about-us/AboutUsPage.vue
  frontend/src/routes/guide/GuidePage.vue
  frontend/src/routes/index/IndexPage.vue
  frontend/src/routes/questions-methodology/QuestionsMethodologyText.md
Labels: enhancement

#572 Hardcode link to Google Sheet on result page
  frontend/src/routes/result/ResultPage.vue
Labels: enhancement

#574 Update Slovak national voting calculator data
  data/instance/volebnakalkulacka.sk/nrsr-2023/inventura-2020-2023/questions.json
Labels: enhancement, data

#575 Fix few more translations
  frontend/src/i18n/locales/cs.json
  frontend/src/i18n/locales/sk.json
  frontend/src/routes/result/ResultPage.vue
Labels: bug, frontend, refactoring

#576 Update Slovak national voting calculator data
  data/instance/volebnakalkulacka.sk/nrsr-2023/inventura-2020-2023/questions.json
Labels: data
